---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-secret
  namespace: ecommerce-dev
spec:
  encryptedData:
    OTEL_EXPORTER_OTLP_ENDPOINT: AgBuMQ1DQJ6Ou5Tn64z3TQ3opvrrNKYNJURWtVtB/N1uSgWXEGCNq9yhFjaRDozrNLQGVxkxUnrZt/0zFxbBzdPJJGjfUUDn9L5H929nQc7oGDCZ2CGuh8LXMlWo3L2vVHhje+Z3+r3TiVky8w3tj90W8EeMsIQFyhy4DHXIcjnldk6wB2Hv7jx9oyWxbX8icO1aFICQEiLqi7qSX8cCDENZ06jKJbhvePRloO9zeA+f1WSNdRxUF7rzCObrEBN3fpYNXU28ITFBneCSb4hIW9cpngutUVhXfAkWyAppj+alP4VBic3Daa8KSya8xPDFuP5Ynx9ugxDU47r7ziO9iyrnrSByhf+twTbgyWfd2y7nvS1RLpli+cfQDD8njWMl1yzVN7ky0zin9lzF35D54sp7FGF/12Pme9wUasQt+N4jb+RxR669PJyJXhiyrBNk0T8oEDS/zehFGfimEEdZZaI3L/yTW8wcsWSZEgu39ABZ8V8I9XQBMxAsCo/kiz4acN7AKUqYA5XZT1tVs3EJPlzhXp9FOh7auH9g1ib+GWe29Lbp4wv06/rf8KSa5z6yatBpRZkG3Bmoz89oAvStBQo/VVh7VYithz56LSkeXXNVvVx2gCI83kelC/MFq+R+EW8u2e13LyrU+tHui3vFrb4ajz9f2roKIKtJl/wIVRvxuQtfI1bIKk8MvSLb1Agjd6B8iM4+53LmLV99mTp8JUMTHMmXCOUPN67FdhDNs9d2Y+lmu6gMDA==
  template:
    metadata:
      name: kafka-secret
      namespace: ecommerce-dev
    type: Opaque
