---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-secret
  namespace: ecommerce-dev
spec:
  encryptedData:
    OTEL_EXPORTER_OTLP_ENDPOINT: AgAdIMMC8Vpe+ImXeyJZW0AQ0c1PsZ6iZfmQ3MG+q/2GaUY7Xfd1X0aKVUiODdeKFiizjgd2MS9nncM2S8azok2X+j2spC+GIDyFz46cSQQGQlH5z1H+XbiwgaO0kpEBC/68BvrmrPgwRAmYOABkRlq/EJRYQ/r3C4VKVVkeLpiveUxK34SzVB2XTBiSgYo10W3lT992yLxTbP4Qbl2GVo/EnIH1GGO6GLGsl77D6pK3CSQSUntgTTxn8IGH0r7A7LZC9SLzFy/jMko9jahcd0RvtJWtrofkUUXkM2FaBJa6BmQb0Dc1uV/EAaIQjzsZGhzWMfrB66u4DAOLIv4PQz2us41R7z5KnE7j+cumgaW2tlH5ZjL+j2J1kiHmIZXHYI0bn8IbJLCRhXbArZy15EqbLGuDMBTY56h9ncfaXaDisLXe3WCdWhFPYlHvqmJymb8pcMzZhLjDUkyIGf49OOPLRgBoZOdNPHF8tdxY8mBuTZHCwUIVqr9hsQTh6HybjB+HVcHQulcFfSv2EXn654QvrbLi/mDFi+r4t4c4dT3kkm/RH7nNPQZytBQmu6/hi1p29hsHMdmO0eMpD3+VhYNLDCamUsyEUJrt82WTjrBpOspcNo4/oRGLMHPxF40hrHS/4ehiiE/qmiosb9prYZJ7FiCOXw4K55yl1LydMrRwR3er0VwnrEEK8Ima0ubofPgr173/YlyitxYbTa9daRGyuqDcD+Ic0c7nEt0EqH0oelj75wkXsQ==
  template:
    metadata:
      name: kafka-secret
      namespace: ecommerce-dev
    type: Opaque
