---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: accountingservice-secret
  namespace: ecommerce-dev
spec:
  encryptedData:
    OTEL_EXPORTER_OTLP_ENDPOINT: AgBVcjg62T5Amz8GadUPFqohFQQfaOL73J++g2FwKqULjT9Dhx7JzAXrxJSxD2f1bbSLih2pkcxJos6TKIJAqsd0LD+ssf2fwCmGYZjcpNQDJUP3c1Vo2KcAcK7EmWqZ3yhbrllXhLProlLbvxxXMFDyslRuykjchgipkXe1ysGr5s/c35j5gV3hP9tmCCWcXw1PjBTzvOFboYwt+UeHl5DyMcPSxhOpLHdeufnFgU9czGu6hVOyH6eafkCirBvMFxJqT+Kh2uTUmpYgnqo4aDNPsBUJoHi7QOTeP4lRqtuG6yKoKersM0LdM8mGP3UvX3Gzw69XlGGGOBlVsabPYjh+b5/N8o1tIFOovvdsyM5DEo+D7H0uu1BRmJukW0TzLS7FBxqbHF5oSAl4hZSjT32lXCtDvpejT86SoWKHWp5aA1n7kxyg50Ea522iAB9a3A3Do5yXhLoKC4YhXqVqiMQyIji4UDekHxHFJ5Yo/QTiUwdyTzWDK/Yy6LInEHlGtRAtH8XOm+bPDvT1TIS+LWjUvdlMQ+GDZBOpDKqXLwd+ZC1lnCDyhbEynWgzQEB2GlVGCHBppFgBj6IJGesueljg2hMyQlPhEsxfxAdD/pXO2sEcB5VfodSpJl9qn3/PKHMLw5jL1DXCFH6IklOaOkHfZk6Pg+aQT0E7Q7ZsGTi7txb9er5rzX/J55bmwzQbmk301hgcvqEPVuRUHRhY1EbdVLGgNEzzDl4alN6u0y+BfRk5IWpVug==
  template:
    metadata:
      name: accountingservice-secret
      namespace: ecommerce-dev
    type: Opaque
