---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: accountingservice-secret
  namespace: ecommerce-dev
spec:
  encryptedData:
    OTEL_EXPORTER_OTLP_ENDPOINT: AgCh8UiZmsYZUNaeThpP+FWzKM5nIgn5bZ/jRecmy37kqUF8Of1MhpqvOgJBm1+SwmqmKOX9IdZgZOZ53K8pdPaEYdnVF670HobmVrXBjrq2LSFlpLWXE/KttCa+LSarvIF2oIGyP0eVfVQYGgktPHmsPx8oMLeVfLVUlRLT+q/gvubXAqhFv6r/+E+76cFjGSXNbJ3/ddKMuO69oeuI/+ID4sz16RiZmcK8SxAA1ZaNmviWd5+fnR7ZqmlHwJJDvkiPy4nb1tb2eQLQsahNgRlc9kruPi7+Az0ENfg5av25qArR3IXraO/ZPU6dh8lib6umYwOI8W6j8SMth0VMqqbCdpEYeF1DbO3k/aOMVEhTOrXi/e4SNqSRnjA/9jvhOsG5rgOoIgLi6yFXtZzqzprl4aFVuISaKe30yXaJYL+CMhJfF9BE5fTv3xFd2yR8DaA9F2rt+cns8fPYvxATD7Hfj3qlgWq0i2y8DHNvxQVmN5RB/yZuOFSh8J7XTf66eIQ0pBUPa5UGi9tkAq5p3aBoLfovVFoTN6OixT4UK1JvLa46caBbVpnHRU6vGJIgNPLu/iLYvHSFrDgZ6zYmzEMl2vK+Xw9vZ1DQMEaQVNtFYbvyQ1NXPtkNVQrkdN3cliC3AQUimGKlMEuL+iKj+lWq02Kiz4BHGmBduco80lXRAWiEb7LQVTlAIWWA8IksXWB5f3j++ScZxgbKgr2m6SE2uYVM5QcaKw+N5WjmtxxFClC9lf+eYQ==
  template:
    metadata:
      name: accountingservice-secret
      namespace: ecommerce-dev
    type: Opaque
