---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: productreviewservice-secret
  namespace: ecommerce-dev
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgDfzYYTfPjFxSiCXQ/723ijyr07RCKsk8+wh7xOfTVSMm/4D+VF5q6v3DcXVzTDavwxafbJtkCkUjDoUFgGjzfQBChXYfKcrnzOG109wGmbrPWuZiorm7Y0kcelMr7Fvd8OxslFoW3CON/Z9Q75iPd52TUX6QPGlj3RDlTIKHJHUfL+ddC6t5rJDStM7d931ORugyWwV/P53qq5qEkO5eFPb1yWTgLwBalxZ552lpLzn459R0JADMuFDpz9qQZiAF8dQtC+Q+lXxjIXDakpan+5jvVelk+q+dQwbw5GH49N8ng3L4axT7rzf69+9DWJDkMs62AdU3t2TdRCM7S3KSFF5VT7X3DmkXMqCBTXleNwHPiikSvvH9GY16vDZUPq+Fx7dUbUPY2nlv1ciB7OlE+jYzBYMtnwYMBClBJEZf6hlcBAgcE9jLmguhGkK+YbTFFnhA/nfQCM2AZI+IPUilSrvkXog5xtSpZvQm++itf6SKy1H0oqnI/Nu/D1JY3+qvBggyFXnAMc73yCQYo1Ui6dO8KGehTTTNC8nYtMMVP/0yAwiGnJ5T4Pwclc2xIr+QgxkX2gSgGfaVh1kePzOzYMCPOtGeIUhNovCdKOeZkFNmYDE5HVHI3qqc/PHoBiqp/O2yiRKtTgCy/do7j1ZOgic0W7kteSP0mbaB3RJss1+Ca4WEvSqEyDK6IubJzACXlP8BA/bqVSioneLRYUhElpG3Sv3h97ngpJfkJliz/DkFW6Kt6Hem5aQ21s
    OPENAI_API_KEY: AgAkHrgjE0eper+noRjLq7d/AJB+vIZoDgZ/UIg7MVOOKbG7fGfSDIXRjkil9m+IFtVp34eTCQJDM0sNeHNy+fN7tE24talZhfWve8hVKlp6iieDrAv8gvLHsK78K0c3nnM7Ztd0u7Suda4FDR5KdsTJTDgDXLptRpYxv3zUCDy/tuZ5FWUDnm58rZNZddK1gJCNbck8ocvA0EIsiSxU24XDWxSRubgnIKVT8jSUncsllLk/IxENYKi31UAK0mz19O/yR0N0jk/8/DEvUPr6pw1zSO5QlL4N9ghnQLeP2jyMKNmjKlGjeSvGTVeYUO5yYkvzbWVQ7w3x58ax3wkSbxy5Iwx2SnOiZmTUw5OxbbsSzGRk3KKZFSEXSjB8ykg30+mMiWXZhpZ3nRz7e/zQFxN6N0dcHr+M4bE4J4QttIdi65h8lRfhVB5YP94LhhSwwtQIrl8C0mLOTSRN6NeKPMQ5ndj4RT4Vr7TnNcWMIcwqBK1nnKte37W3c1Ly+zF0zoAE7aw+XJlR9jLxX0j5jrsII/fagS7Y5bXrL/y5ifzdvLXXkjwVYTYksP+W3CheNYyay7PxjQ+wBum5jRAWMYu/jxG0MB4xcbXIK8g6NFo8+xTqxOsEHenCnV0EW7c0DwYyyYzgyj1OtZ2U+DkAd+YOPE7+Q2NXm8Ll2iNPqwEBbwKZMkNic6jcEbmqEpQo6p5oNz8xBpU=
  template:
    metadata:
      name: productreviewservice-secret
      namespace: ecommerce-dev
    type: Opaque
