---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: productreviewservice-secret
  namespace: ecommerce-dev
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgBvWSne9MihQU2PreKOEulJBd2YYx47wsufSTGKK7wSyZqeKfZyE9hbHCwvVu14kz7ff0AcTTSMWi/qIXYoR1PVLyCDTQc0aWtGm7LhowAHWbepnJmvbjiaVIrNTBAOX74rfvh1wT3sIGy3LIJEQ6AAWoOzSQ/zB1asAiBUo70JK02eXXJInHfXDTjGVvmqTS8puIjJsgUeKvmHJOhi32pATZk9rZL7XiO+6TDmILPPXemtmgPQwHA57f4NnOgWrUkd68yprGwq1+wRhI2N4Q18tXouzLa1cJB4vWzLhY4mX7kkBAdRKklYuXvA5idwbiww7kiexnoWp4Xt/VyeexaTy0a9Vy016yOStBIB1Xhi+jC+uaznbIHpkVaml83ZFFcnvUdHQnmYECJh74SwVNc35Bumrd/ziYFlGqHCa3qrOpVQ8zvgMyYUc5GMq8ogSV9FmSCUxIdh6RQRHSjywiyDfyHxBuvZ+DG2Xm3RHX+dhqgxEuXC/NzCbbA3wBRSCQPlG8ZDGJOBtc52d9ycihKRSawwl37qxPJUQhDyLsdZ139Ef39QAwXJB2TAlv+8Vbze/m9kqzfgDYse19wEWWUl9/ooGMIKY7vmGEhG6msU+5RCAoJVXoZYkYlk2OG+dp0zjKN4wsrQ6jCEMilFgw1uWH9hQuqzDfGja/JSEFgE+ivfhQhQuNik9D2oIofifpNOWHOjqG4DgZrkKtdxJw/W+sp/gSov87Xs2hmVCxq6Uzrdb2NdxDAYkugE
    OPENAI_API_KEY: AgA289f+SJfhsFD4+nYiZZSb7pqhzdhjQ/EqLJO1+vvg+CnTQ8hJHfTeo/qdTQC4dIfzxW68RqE8O/2Yz3BdHeOtFxGlQdZ0aPE88XWOvBTeDBgO6NoCOztCJUhV5p+U7JzrYbz78REvTdsgcqTnz7BC/1+YXkOPSBFeC8FeIgrkUWvPH3n1ogzIsEYz4KV9dbjx2we1pJQw9vkmZ6oXzgqV+83xZ51e3G72VW1QWHPBqwdoLeh6E/mMIdMy107emM0cLGUFwkPZI686WwXnbclvOYQvSngnCj4pm7zWEJFyAwn7L53HcFcULb+KutqgIqYq38r+LZIhB9ZDd+PR7CkZHDYpSa/+FQA+iVY+603PPvkTgljGmufKpzKP4imKcdw4FUQ7jnBDHe0nZy6zfsF8n7/BnD57K7pTadWD0GGohGR947ITCzNQ1rOrsE4A621EKz92Ft4UGX1fu7KahYYiP6iSMyqduhL2HXC4S7qcPvDzDDlFNTJy7lr4o9Z5yjJE8dbzU7DM87mLkQDdFDkvbkeDrKeDtpWQxTa2tUrRclTw49j2ypcV3DXu6hzoeoQetgpHSNyWL8eiF+uBV0GsYYo7mZFX8UOo4W+IvxW+uNNKag86+78uaDBxCWNhNv/tyeMWvnloSZ6zuybQTsEdWMAju/T7lqnVFE0DyQBQ2sjlUC7EMK4c54mFsB+3PhUrCdI2jOA=
  template:
    metadata:
      name: productreviewservice-secret
      namespace: ecommerce-dev
    type: Opaque
