apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-dev
resources:
  - ../../base

patchesStrategicMerge:
  - patches/frontend-deployment.yaml
  - patches/frontendproxy-deployment.yaml
  - patches/kafka-deployment.yaml
  - patches/llmservice-deployment.yaml
  - patches/paymentservice-deployment.yaml
  - patches/cartservice-deployment.yaml
  - patches/productcatalogservice-deployment.yaml
